variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 
    ApimPolicyRoot: '$(Build.SourcesDirectory)\Resources\ApimPolicies'

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: trivedihimanshu/master-dfc-devops
    type: github
    name: trivedihimanshu/master-dfc-devops
    endpoint: trivedihimanshu

jobs:

- job: BuildAndTestArmTemplate
  displayName: BuildAndTestArmTemplate
  pool:
    vmImage: 'windows-latest'
    demands:
    - msbuild
    - visualstudio

  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@trivedihimanshu/master-dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)

  - task: CopyFiles@2
    displayName: 'Copy APIM policies to staging'
    inputs:
      SourceFolder: $(ApimPolicyRoot)
      TargetFolder: $(build.artifactstagingdirectory)/Azure/ApimPolicies

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: AzureResources